exp_name: mofnet

# model
latent_dim: 128
hid_dim1: 64
hid_dim2: 32
desc_dim: 7


#dataset
topo_size: 964
node_size: 649
edge_size: 220
train_data_dir: /home/users/seunghh/_hd1/autollm/mof2zeo/mof2zeo/data/train.csv
valid_data_dir: /home/users/seunghh/_hd1/autollm/mof2zeo/mof2zeo/data/valid.csv
test_data_dir: /home/users/seunghh/_hd1/autollm/mof2zeo/mof2zeo/data/test.csv
feature_name_dir: /home/users/seunghh/_hd1/autollm/mof2zeo/mof2zeo/data/feature_name.txt
mean_dir : /home/users/seunghh/mofgen/easy_adapt_mof/easy_adapt_mof/data/test_prev/mean_all.csv
std_dir : /home/users/seunghh/mofgen/easy_adapt_mof/easy_adapt_mof/data/test_prev/std_all.csv


#training
seed: 1
num_workers: 4
batch_size: 256
learning_rate: 0.001
weight_decay: 0.01
lr_mult: 1
end_lr: 0
decay_power: 1
optim_type: adamw
warmup_steps: 0.05
max_epochs: 500
resume_from: 
per_gpu_batchsize: null
num_nodes: 1
save_true: True









