#!/usr/bin/env python3
"""
Full MOF Simulation Pipeline
Runs: matchmaker -> filter_candidate -> generate_mofs -> optimize -> run_raspa
"""

import os
import sys
import json
import argparse
import subprocess
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "test_run_simulation"

sys.path.insert(0, str(PROJECT_ROOT / "core"))
import matchmaker


def log_step(step: str, msg: str, start_time: float = None) -> None:
    elapsed = f" ({time.time() - start_time:.1f}s)" if start_time else ""
    print(f"\n{'=' * 70}")
    print(f"[{step}] {msg}{elapsed}")
    print("=" * 70)


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def load_input_json(input_path: str) -> dict:
    with open(input_path, "r") as f:
        return json.load(f)


def run_matchmaker(data: dict) -> dict:
    print("Running matchmaker to get valid topology/node/edge...")

    mm = matchmaker.Matchmaker()

    specs = {}

    if "node_query" in data:
        specs["node_query"] = data["node_query"]
    if "linker_query" in data:
        specs["linker_query"] = data["linker_query"]
    if "global_requirements" in data:
        specs["global_requirements"] = data["global_requirements"]

    matchmaker_result = mm.smart_matchmaker_single_node(specs)

    print(
        f"Matchmaker results: {len(matchmaker_result.get('topology', []))} topologies, "
        f"{len(matchmaker_result.get('node', []))} nodes, "
        f"{len(matchmaker_result.get('edge', []))} edges"
    )

    return matchmaker_result


def main():
    total_start = time.time()

    parser = argparse.ArgumentParser(description="Full MOF Simulation Pipeline")
    parser.add_argument(
        "--input_json", type=str, required=True, help="Path to agent2_output.json"
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default=str(DEFAULT_OUTPUT_DIR),
        help="Output directory",
    )
    parser.add_argument(
        "--num_mofs",
        type=int,
        default=10,
        help="Number of MOFs to generate",
    )
    args = parser.parse_args()

    input_path = Path(args.input_json)
    output_dir = Path(args.output_dir)

    if not input_path.exists():
        print(f"ERROR: Input file not found: {input_path}")
        sys.exit(1)

    print(f"Input: {input_path}")
    print(f"Output: {output_dir}")

    dirs = {
        "mof_candidates": output_dir / "0_mof_candidates",
        "mof_generation": output_dir / "1_mof_generation",
        "opt": output_dir / "2_opt",
        "gcmc": output_dir / "3_gcmc",
    }
    for d in dirs.values():
        ensure_dir(d)

    total_start = time.time()
    step_start = total_start

    data = load_input_json(input_path)

    if "proposals" in data and "ranked_mofs" in data["proposals"]:
        log_step("0", "Using existing ranked_mofs from input")
        ranked_mofs = data["proposals"]["ranked_mofs"][: args.num_mofs]
        output_json = dirs["mof_candidates"] / "test_result_agent3.json"
        with open(output_json, "w") as f:
            json.dump({"proposals": {"ranked_mofs": ranked_mofs}}, f, indent=2)
        print(f"Saved ranked MOFs to: {output_json}")
    else:
        log_step("0", "Running matchmaker + filter_candidate")

        matchmaker_result = run_matchmaker(data)

        constraints_file = output_dir / "temp_constraints.json"
        constraints_data = {
            "matchmaker_result": matchmaker_result,
            "geometry_filter": data.get("geometry_filter", {}),
        }
        with open(constraints_file, "w") as f:
            json.dump(constraints_data, f, indent=2)

        cmd_filter = [
            sys.executable,
            str(Path(__file__).parent / "filter_candidate.py"),
            "--output",
            str(dirs["mof_candidates"] / "test_result_agent3.json"),
            "--top_n",
            str(args.num_mofs),
            "--constraints",
            str(constraints_file),
        ]
        subprocess.run(cmd_filter, check=True)

        output_json = dirs["mof_candidates"] / "test_result_agent3.json"

        with open(output_json, "r") as f:
            result_data = json.load(f)

        if not result_data.get("proposals", {}).get("ranked_mofs"):
            print("ERROR: No MOF candidates generated by filter_candidate")
            sys.exit(1)

        print(f"filter_candidate output: {output_json}")
        print(f"[0] Completed in {time.time() - step_start:.1f}s")
        step_start = time.time()

    log_step("1", "Running PORMAKE (MOF CIF generation)")

    generate_input = dirs["mof_candidates"] / "test_result_agent3.json"
    core_dir = Path(__file__).parent

    cmd_generate = [
        sys.executable,
        str(core_dir / "simulation" / "generate_mofs.py"),
        "--mof-dir",
        str(dirs["mof_generation"]),
        "--result_file",
        str(generate_input),
        "--max",
        str(args.num_mofs),
    ]
    subprocess.run(cmd_generate, check=True)
    print(f"[1] Completed in {time.time() - step_start:.1f}s")
    step_start = time.time()

    log_step("2", "Running LAMMPS optimization")

    cif_files = list(dirs["mof_generation"].glob("*.cif"))
    print(f"Found {len(cif_files)} CIF files in {dirs['mof_generation']}")

    cmd_opt = [
        sys.executable,
        str(core_dir / "simulation" / "opt" / "optimize.py"),
        "--cif-dir",
        str(dirs["mof_generation"]),
        "--output-dir",
        str(dirs["opt"]),
    ]
    subprocess.run(cmd_opt, check=True)
    print(f"[2] Completed in {time.time() - step_start:.1f}s")
    step_start = time.time()

    log_step("3", "Running RASPA3 GCMC simulation")

    opt_cifs = (
        list((dirs["opt"] / "optimized_cifs").glob("*.cif"))
        if (dirs["opt"] / "optimized_cifs").exists()
        else []
    )
    if opt_cifs:
        raspa_cif_dir = dirs["opt"] / "optimized_cifs"
        print(f"Using {len(opt_cifs)} optimized CIFs from {raspa_cif_dir}")
    else:
        raspa_cif_dir = dirs["mof_generation"]
        print(f"Using {len(cif_files)} original CIFs from {raspa_cif_dir}")

    cmd_raspa = [
        sys.executable,
        str(core_dir / "simulation" / "gcmc" / "run_raspa.py"),
        "--mof-dir",
        str(raspa_cif_dir),
        "--output-dir",
        str(dirs["gcmc"]),
    ]
    env = os.environ.copy()
    pythonpath = env.get("PYTHONPATH", "")
    env["PYTHONPATH"] = f"{PROJECT_ROOT}:{core_dir}:{pythonpath}"
    subprocess.run(cmd_raspa, check=True, env=env)
    print(f"[3] Completed in {time.time() - step_start:.1f}s")

    log_step("COMPLETE", f"Pipeline finished! Total: {time.time() - total_start:.1f}s")
    print(f"\nResults saved to: {output_dir}")
    print(f"  0_mof_candidates: {dirs['mof_candidates']}")
    print(f"  1_mof_generation: {dirs['mof_generation']}")
    print(f"  2_opt: {dirs['opt']}")
    print(f"  3_gcmc: {dirs['gcmc']}")


if __name__ == "__main__":
    main()
