"""Unified JSON schema for PORMAKE building block metadata.

This module defines the canonical data structures for both Edge and Node
building blocks. Every field is documented with its source (deterministic
vs rule-based vs LLM) and data type.

Design principles:
  1. Layer 1 (Facts) is NEVER generated by an LLM — only deterministic code.
  2. Layer 2 (Semantics) is tagged with its source method.
  3. Provenance tracks exactly how and when each JSON was created.
  4. Validation is self-contained — each JSON proves its own correctness.
"""

from __future__ import annotations

from dataclasses import dataclass, field, asdict
from typing import Optional
from enum import Enum
import json


# ── Enums ──────────────────────────────────────────────────────────────

class BBType(str, Enum):
    EDGE = "edge"
    NODE = "node"


class ValidationStatus(str, Enum):
    PASS = "pass"
    WARN = "warn"
    FAIL = "fail"


class SemanticSource(str, Enum):
    RULE_BASED = "rule-based"       # SMARTS matching, deterministic rules
    LLM_GENERATED = "llm-generated" # Tagged LLM output
    PENDING = "pending"             # Not yet enriched


# ── Layer 1: Deterministic Facts ───────────────────────────────────────

@dataclass
class ConnectionPoint:
    """A single dummy atom (X) connection point."""
    atom_index: int                    # 0-indexed position in XYZ
    coordinates: list[float]           # [x, y, z]
    bonded_to_index: int               # index of the real atom it connects to
    bonded_to_element: str             # element of that real atom
    bond_type: str                     # S, D, T, or A


@dataclass
class ConnectionPointsSummary:
    """All connection points for this building block."""
    count: int
    points: list[ConnectionPoint]
    connection_chemistry: list[str]    # element at each anchor, e.g. ["C", "C"]
    distance_matrix: list[list[float]] # pairwise distances between X atoms


@dataclass
class BondGraphSummary:
    """Summary of the molecular bond graph (excludes X atoms and their bonds)."""
    num_bonds: int
    bond_type_counts: dict[str, int]   # {"S": 12, "A": 18, "D": 0, "T": 0}
    num_rings: int                     # from cycle basis
    ring_sizes: list[int]              # sorted list of ring sizes
    is_connected: bool                 # single connected component (excl. X)


@dataclass
class MetalCoordination:
    """Coordination environment for a single metal atom (nodes only)."""
    metal_index: int                   # 0-indexed in XYZ
    element: str                       # e.g. "Fe"
    bonded_atoms: list[dict]           # [{"index": 12, "element": "N", "bond_type": "S"}, ...]
    coordination_number: int           # len(bonded_atoms)


@dataclass
class Layer1Facts:
    """Deterministic facts computed from XYZ + bond block. No LLM involvement."""
    # ── Identity ──
    formula: str                       # Hill notation, excludes X
    molecular_weight: float            # Da, excludes X (mass=0)
    atom_counts: dict[str, int]        # {"C": 18, "H": 12}, excludes X
    total_atoms: int                   # excludes X

    # ── Connectivity ──
    connection_points: ConnectionPointsSummary
    bond_graph: BondGraphSummary

    # ── Metals ──
    metals: list[str]                  # unique metal elements found, sorted
    has_metal: bool

    # ── Structural ──
    is_rigid: bool                     # deterministic: no rotatable non-ring single bonds
    degree_of_unsaturation: float      # (2C + 2 - H + N - Halogen) / 2
    num_rings: int                     # from cycle basis
    is_planar: bool                    # all atoms ~coplanar (z-range < 0.5 Å)

    # ── Representations ──
    smiles: Optional[str]              # with * for connection points; null if failed
    smiles_canonical: Optional[str]    # RDKit canonical; null if failed
    selfies: Optional[str]             # SELFIES encoding; null if failed
    smiles_method: str                 # "explicit_bond_block" | "geometry_fallback" |
                                       # "partial_organic" | "failed"

    # ── Charge ──
    net_charge: int                    # from protonation state of SMILES (0 if unknown)

    # ── Edge-specific (null for nodes) ──
    length_angstroms: Optional[float]  # max Euclidean dist between X atoms
    topological_distance: Optional[list[list[int]]]  # pairwise shortest graph paths between X atoms

    # ── Node-specific (null for edges) ──
    nuclearity: Optional[int]          # count of metal atoms (0 for organic nodes)
    geometry_inferred: Optional[str]   # "tetrahedral" | "octahedral" | "square_planar" | etc.
    metal_coordination: Optional[list[MetalCoordination]]  # per-metal coordination env


# ── Layer 2: Semantic Enrichment ───────────────────────────────────────

@dataclass
class FunctionalGroups:
    """Functional group assignments, separated by detection method."""
    backbone: list[str]                # SMARTS-matched on core scaffold
    substituents: list[str]            # SMARTS-matched on branches
    rule_based: list[str]              # all SMARTS-detected (union)
    rule_based_counts: dict[str, int]  # e.g. {"nitro": 4, "benzene_ring": 2}
    llm_additions: list[str]           # LLM-detected (tagged separately)


@dataclass
class AbstractFeatures:
    """Boolean feature flags. Rule-based or LLM-enriched."""
    is_fluorinated: bool
    is_electron_deficient: bool
    is_electron_rich: bool
    is_symmetric: bool
    is_conjugated: bool
    is_metalated: bool
    has_hydrogen_bond_donor: bool
    has_hydrogen_bond_acceptor: bool
    is_charged: bool
    is_photoswitchable: bool
    # Node-specific
    has_open_metal_site: Optional[bool]  # coordination_number < typical


@dataclass
class Layer2Semantics:
    """Semantic enrichment layer. Every field tagged with source method."""
    source: SemanticSource             # how this layer was populated
    readable_name: Optional[str]       # human-friendly name
    functional_groups: FunctionalGroups
    core_scaffold: list[str]           # e.g. ["terphenyl", "biphenyl", "benzene"]
    abstract_features: AbstractFeatures
    design_hints: Optional[str]        # LLM reasoning context for MOF design

    # Node-specific enrichment (null for edges)
    sbu_type: Optional[str]            # e.g. "Zn4_Carboxylate_Paddlewheel_4c"
    ligand_chemistry: Optional[list[str]]  # donor atom types, e.g. ["O", "N"]
    oxidation_states: Optional[dict[str, int]]  # e.g. {"Fe": 2}
    spin_state: Optional[str]          # e.g. "high-spin d5"


# ── Provenance ─────────────────────────────────────────────────────────

@dataclass
class Provenance:
    """Full traceability for how this JSON was generated."""
    pipeline_version: str
    schema_version: str
    generated_at: str                  # ISO 8601 timestamp
    source_file: str                   # e.g. "E1.xyz"
    source_file_sha256: str            # hex digest
    tool_versions: dict[str, str]      # {"rdkit": "2024.03.1", ...}
    dummy_atom_placeholder: str        # "Lr" — element used in RDKit for dummy atoms (X→Lr, Z=103)
    layer1_method: str                 # always "deterministic"
    layer2_method: str                 # "smarts_rules" | "llm-gemini" | "pending"


# ── Validation ─────────────────────────────────────────────────────────

@dataclass
class ValidationReport:
    """Self-verification results for this building block."""
    status: ValidationStatus
    checks: dict[str, bool]            # {"formula_consistent": True, ...}
    warnings: list[str]
    errors: list[str]


# ── Top-Level Record ───────────────────────────────────────────────────

@dataclass
class BBRecord:
    """Complete building block metadata record.

    This is the canonical JSON structure written to disk for each
    building block (edge or node).
    """
    bb_id: str                         # e.g. "E1" or "N100"
    bb_type: BBType                    # "edge" or "node"
    layer1_facts: Layer1Facts
    layer2_semantics: Layer2Semantics
    provenance: Provenance
    validation_report: ValidationReport

    def to_dict(self) -> dict:
        """Convert to JSON-serializable dict."""
        return _to_serializable(asdict(self))

    def to_json(self, indent: int = 2) -> str:
        """Convert to formatted JSON string."""
        return json.dumps(self.to_dict(), indent=indent, ensure_ascii=False)


# ── Helpers ────────────────────────────────────────────────────────────

def _to_serializable(obj):
    """Recursively convert Enum values to their string representation."""
    if isinstance(obj, dict):
        return {k: _to_serializable(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_to_serializable(v) for v in obj]
    if isinstance(obj, Enum):
        return obj.value
    return obj


# ── Factory for empty/pending Layer 2 ──────────────────────────────────

def make_pending_layer2() -> Layer2Semantics:
    """Create a Layer 2 with all fields set to pending/empty defaults."""
    return Layer2Semantics(
        source=SemanticSource.PENDING,
        readable_name=None,
        functional_groups=FunctionalGroups(
            backbone=[],
            substituents=[],
            rule_based=[],
            rule_based_counts={},
            llm_additions=[],
        ),
        core_scaffold=[],
        abstract_features=AbstractFeatures(
            is_fluorinated=False,
            is_electron_deficient=False,
            is_electron_rich=False,
            is_symmetric=False,
            is_conjugated=False,
            is_metalated=False,
            has_hydrogen_bond_donor=False,
            has_hydrogen_bond_acceptor=False,
            is_charged=False,
            is_photoswitchable=False,
            has_open_metal_site=None,
        ),
        design_hints=None,
        sbu_type=None,
        ligand_chemistry=None,
        oxidation_states=None,
        spin_state=None,
    )
